<?php

namespace Tests\Feature;

use App\Thread;
use App\Trending;
use Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;

class TrendingThreadTest extends TestCase
{
    use DatabaseMigrations;

    protected $trending;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->trending = new Trending('test_trending');
        $this->trending->reset();
    }

    /** @test */
    public function it_can_increments_score_of_threads()
    {
        $this->assertEmpty($this->trending->get());

        $thread = create(Thread::class);
        $this->get($thread->path());

        $this->assertCount(1, $this->trending->get());
    }
}
